basetheme_bootstrap/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import RedirectView

from basetheme_bootstrap import views
from basetheme_bootstrap.forms import AuthenticationForm

app_name = 'basetheme_bootstrap'
urlpatterns = [
    ################################################################################
    # Account management
    ################################################################################
    path('accounts/', views.account_detail, name='account'),
    path('accounts/profile/', RedirectView.as_view(url=reverse_lazy('basetheme_bootstrap:account'))),
    path('accounts/login/', auth_views.LoginView.as_view(form_class=AuthenticationForm), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/password/', views.change_password, name='change_password'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/edit/', views.user_update, name='user-update'),
    path('accounts/remove/', views.user_delete, name='user-delete'),
    re_path('accounts/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/',
        views.activate, name='activate'),
    ################################################################################
    # Lost password
    ################################################################################
    path('accounts/password_reset/',
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("basetheme_bootstrap:password_reset_done"),
        ),
        name='password_reset'),
    path('accounts/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    re_path('accounts/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("basetheme_bootstrap:password_reset_complete"),
        ),
        name='password_reset_confirm'),
    path('accounts/password/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    ################################################################################
    # About page
    ################################################################################
    path('about/', views.about_page, name='about_page'),
    ################################################################################
]

basetheme_bootstrap/models.py
from django.db import models

# Create your models here.

basetheme_bootstrap/forms.py
from django import forms
from django.contrib.auth import get_user_model, forms as auth_forms
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.forms import widgets
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from basetheme_bootstrap.default_settings import (
    is_username_is_email,
    is_first_last_name_required,
    get_failed_login_exponential_backoff_gradient,
    is_failed_login_exponential_backoff_enabled,
)


class CleanUsernameAndSuggestReset:
    class Meta:
        abstract = True

    def clean(self):
        f = super().clean()
        qs = get_user_model().objects
        if hasattr(self, 'instance'):
            qs = qs.filter(~Q(id=self.instance.id))
        if qs.filter(email=f["email"]).exists() or \
                not is_username_is_email() and \
                qs.filter(username=f.get("username", "")).exists():
            self.add_error("email", mark_safe(_(
                'The email already exists, if you have lost your password you can reset it '
                '<a href="%s">here</a>.') % (reverse('basetheme_bootstrap:password_reset'))))
        if is_first_last_name_required():
            if len(f.get("first_name", "")) == 0:
                self.add_error("email", _("First name is required"))
            if len(f.get("last_name", "")) == 0:
                self.add_error("email", _("Last name is required"))
        return f


class UserCreationFormWithMore(CleanUsernameAndSuggestReset, auth_forms.UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name")
        field_classes = {'username': auth_forms.UsernameField}

    next = forms.CharField(widget=widgets.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(UserCreationFormWithMore, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        if is_username_is_email():
            del self.fields['username']
        if is_first_last_name_required():
            self.fields['first_name'].required = True
            self.fields['last_name'].required = True

    def save(self, commit=True):
        user = super().save(commit=False)
        if is_username_is_email():
            user.username = user.email
        if commit:
            user.save()
        return user


class MyUserChangeForm(CleanUsernameAndSuggestReset, auth_forms.UserChangeForm):
    password = None

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if is_username_is_email():
            del self.fields['username']
            self.fields['email'].required = True
        if is_first_last_name_required():
            self.fields['first_name'].required = True
            self.fields['last_name'].required = True

    def save(self, commit=True):
        user = super().save(commit=False)
        if is_username_is_email():
            user.username = user.email
        if commit:
            user.save()
        return user


class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ()


class AuthenticationForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if is_username_is_email():
            self.fields["username"].label = _("Email")

    def clean(self):
        if not is_failed_login_exponential_backoff_enabled():
            return super().clean()
        ip_address = self.request.META.get("REMOTE_ADDR")

        # Increment the login attempt count for this IP address
        cache_key = f"login_attempts:{ip_address}"
        login_attempts = cache.get(cache_key, 0)
        cache.set(cache_key, login_attempts + 1, 300)

        # check if lock exists for this ip address
        locked_key = f"locked_login_attempts:{ip_address}"
        locked_login_attempts = cache.get(locked_key, False)
        # expiry of the lock is based on the number of already done login_attempts
        wait_time = min(
            get_failed_login_exponential_backoff_gradient()
            ** login_attempts,
            300,
        )
        cache.set(locked_key, True, wait_time)

        # if locked was found we fail the form validation to prevent successful login
        if locked_login_attempts:
            m = int(wait_time // 60)
            s = int(wait_time - 60 * m)
            # informing the user that zhe has hit the wall and have to wait
            raise ValidationError(
                _(
                    "Too many login attempts ({:d}). Please try again later after {:02d}:{:02d} minute."
                ).format(login_attempts, m, s)
            )
        return super().clean()

basetheme_bootstrap/views.py
import logging
from datetime import datetime

from django.db import router
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.utils import NestedObjects
from django.contrib.auth import update_session_auth_hash, authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.db.models import ProtectedError
from django.forms import widgets
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.template import TemplateDoesNotExist
from django.template.defaultfilters import time as time_filter
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.translation import gettext

from basetheme_bootstrap import tokens
from basetheme_bootstrap import user_preferences_utils
from basetheme_bootstrap.default_settings import is_validating_email
from basetheme_bootstrap.forms import UserCreationFormWithMore, \
    MyUserChangeForm, UserDeleteForm
from basetheme_bootstrap.shortcuts import redirect_same_domain as redirect

logger = logging.getLogger(__name__)

__PENDING_ACCOUNT_USER = "PendingAccountUser"

def get_pending_account_user_group_name():
    return __PENDING_ACCOUNT_USER

def about_page(request):
    context = {}
    try:
        return render(request, settings.BASETHEME_BOOTSTRAP_TEMPLATE_LOCATION_PROJECT + '/about.html')
    except TemplateDoesNotExist:
        return render(request, 'basetheme_bootstrap/about.example.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('basetheme_bootstrap:account')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/small_form_host.html', {
        'title': gettext('Change password'),
        'submit_text': gettext('Save changes'),
        'form': form
    })


def signup(request):
    if request.method == 'POST':
        form = UserCreationFormWithMore(request.POST)
        if form.is_valid():
            auto_active = not is_validating_email()
            next_page = form.cleaned_data["next"]
            user = form.save()
            if get_user_model().objects.filter(pk__gt=1).count() == 0:
                user.is_superuser = True
                user.is_staff = True
                user.is_active = True
                Group.objects.get_or_create(name=__PENDING_ACCOUNT_USER)
            else:
                if not auto_active:
                    g, created = Group.objects.get_or_create(name=__PENDING_ACCOUNT_USER)
                    user.groups.add(g)
                user.is_active = auto_active
            user.save()

            send_account_created(request, user, auto_active=auto_active, next_page=next_page)

            if not auto_active and not user.is_superuser:
                return account_is_pending_view(request, email=request.POST['email'])

            username = user.username
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            request.user = user

            login(request, user)
            return redirect(next_page if next_page else 'home')
        else:
            user = get_user_model().objects.filter(groups__name=__PENDING_ACCOUNT_USER,
                                                   email=request.POST['email']).first()
            if user is not None:
                send_account_created(request, user, auto_active=not is_validating_email())
                return account_is_pending_view(request, email=request.POST['email'])
    else:
        if not request.user.is_anonymous:
            return HttpResponseForbidden()
        try:
            initial = dict(next=request.GET["next"])
        except KeyError:
            initial = None
        form = UserCreationFormWithMore(initial=initial)
    return render(request, 'registration/signup.html', {'form': form})


def account_is_pending_view(request, email):
    return render(request, 'basetheme_bootstrap/simple_message_page.html', {
        'page_title': gettext('Account activation pending'),
        'message': gettext('An email was sent with a link to validate your account, '
                            'please click on the link to enable your account.'),
        'sub_message': gettext('The email has been addressed to %s.') % email,
    })


def send_account_created(request, user, auto_active=False, next_page=None):
    try:
        activation_link = request.scheme + "://" + request.get_host()
        activation_link += reverse('basetheme_bootstrap:activate', kwargs={
            'uidb64': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': tokens.account_activation_token.make_token(user)
        })
        if next_page:
            activation_link += "?next=" + next_page
        if auto_active:
            message = gettext(
                'Dear %(first_name)s %(last_name)s\n\n'
                'Your account have successfully been created on %(joined)s.'
                '\n\n'
                'Best regards') % dict(
                first_name=user.first_name,
                last_name=user.last_name,
                joined=str(user.date_joined),
            )
        else:
            message = gettext(
                'Dear %(first_name)s %(last_name)s\n\n'
                'Your account have successfully been created on %(joined)s.'
                '\n\n'
                'Please click on the link to confirm your registration\n'
                '%(activation_link)s'
                '\n\n'
                'Best regards') % dict(
                first_name=user.first_name,
                last_name=user.last_name,
                joined=str(user.date_joined),
                activation_link=activation_link,
            )
        send_mail(
            subject=gettext('Account successfully created'),
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
            fail_silently=False,
        )
    except Exception as e:
        logging.exception("Sending email to user %i failed" % user.pk)


def user_update(request):
    if request.method == 'POST':
        form = MyUserChangeForm(instance=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your account was successfully updated!')
            return redirect('basetheme_bootstrap:account')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = MyUserChangeForm(instance=request.user)
    return render(request, 'registration/small_form_host.html', {
        'title': gettext('Update account'),
        'submit_text': gettext('Save changes'),
        'form': form,
        'medium_width': True,
    })


def user_delete(request):
    if request.method == 'POST':
        form = UserDeleteForm(instance=request.user, data=request.POST)
        if form.is_valid():
            try:
                user = form.save()
                user.delete()
                update_session_auth_hash(request, user)  # Important!
                messages.success(request, 'Your account was successfully deleted!')
                return redirect('/')
            except ProtectedError as e:
                messages.error(request, gettext("Some data remaining in the system prevent the deletion of your "
                                                 "account. Please either remove these data, or contact the "
                                                 "administrator to solve the issue.\nMessage:\n" + str(e)))
            except Exception as e:
                messages.error(request, e)
    else:
        form = UserDeleteForm(instance=request.user)
    # Inspired from auth/admin.py#get_deleted_objects
    collector = NestedObjects(using=router.db_for_write(get_user_model()))
    collector.collect([request.user,])
    return render(request, 'registration/account_deletion.html', {
        'title': gettext('Account deletion'),
        'submit_text': gettext('Delete account and all related data'),
        'form': form,
        'protected': collector.protected,
        'medium_width': True,
        'btn_classes': 'btn btn-lg btn-danger text-center',
        'btn_container_classes': 'text-center',
        'custom_css_width':' ',
    })


@login_required
def account_detail(request):
    klass = user_preferences_utils.get_user_preference_class()
    if klass is None:
        form_prefs = None
    else:
        is_posted = request.method == 'POST'
        pref = klass.get_for_user(user=request.user)
        widgets_dict = dict(
            (f.name, widgets.CheckboxSelectMultiple()) for f in pref._meta.get_fields() if f.many_to_many)
        form_prefs = forms.modelform_factory(
            klass,
            fields=list(pref.get_allowed_fields()),
            widgets=widgets_dict,
        )(instance=pref, data=request.POST if is_posted else None)
        if is_posted and form_prefs.is_valid():
            form_prefs.save()
            messages.success(
                request=request,
                message=gettext("Preferences successfully saved at %s") % time_filter(datetime.now()),
            )

basetheme_bootstrap/templates/basetheme_bootstrap/about.example.html
{% extends basetheme_bootstrap_base_template %}
{% load i18n %}
{% block title %}{%trans "About"%}{% endblock %}
{% block page_title %}{%trans "About"%}{% endblock %}
{% block content%}
<div class="col-xs-12 col-12">
    <h2>{%trans "Team"%}</h2>
    <table class="table href-break-all">
        <thead>
        <tr>
            <th>{%trans "Last name"%}</th>
            <th>{%trans "First name"%}</th>
            <th>{%trans "Contact"%}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                BRANCOTTE
            </td>
            <td>
                Bryan
            </td>
            <td>
                <a target="_blank"
                   href="https://orcid.org/0000-0001-8669-5525">https://orcid.org/0000-0001-8669-5525</a><br/>
                <a target="_blank" href="https://research.pasteur.fr/en/member/bryan-brancotte">https://research.pasteur.fr/en/member/bryan-brancotte</a><br/>
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock%}

basetheme_bootstrap/templates/basetheme_bootstrap/address.example.html
{% load  sstatic %}
<div class="footer__logo clearfix">
    <img src="{% sstatic '/img/pasteur-white.png'%}" alt="Institut Pasteur" title="Institut Pasteur">
</div>
<div class="block block-block block-block-1">
    <div class="content">
        <root>
        <div class="address_street">
            <span>25-28 Rue du Dr Roux, 75015 Paris</span>
        </div>
        <div class="address_phone"><span>01 45 68 80 00</span>
        </div>
        </root>
    </div>
</div>

basetheme_bootstrap/templates/basetheme_bootstrap/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% load  static %}
{% load  sstatic %}
{% load  basetheme_bootstrap %}
{% load i18n %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    {% block ref_google %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static '/img/favicon.png'%}">

    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script
            src="https://code.jquery.com/color/jquery.color.plus-names-2.1.2.min.js"
            integrity="sha256-Wp3wC/dKYQ/dCOUD7VUXXp4neLI5t0uUEF1pg0dFnAE="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/bootstrap-slider.min.js"></script>

    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.min.css"/>
    <link rel="stylesheet" href="{% static '/css/bootstrap-multiselect.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static '/css/bootstrap-xlgrid.css' %}"/>
    <link rel="stylesheet" href="{% static '/css/basetheme_bootstrap.css' %}"/>
    {% block extra_css %}{% endblock %}

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="{% static '/js/bootstrap-multiselect.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="{% static '/js/basetheme_bootstrap.js' %}"></script>
    {% block extra_js %}{% endblock %}

</head>
<body>
{% include_if_exists "fork_me.html"|localize_template "basetheme_bootstrap/fork_me.example.html" %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home'%}">{% block project_name %}{% endblock %}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{{ request|is_active:'home'}}"><a href="{% url 'home'%}">{%trans "Home"%}</a></li>
                {% include_if_exists "nav_bar.html"|localize_template "basetheme_bootstrap/nav_bar.example.html" %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% block extra_li_dropdown_right %}{% endblock %}
                {%if not request.user.is_authenticated %}
                <li class=""><a href="{% url 'basetheme_bootstrap:login'%}?next={{ request.path|urlencode }}">{% block sign_in_word %}{%trans "Login"%} {% endblock %}<i class="fa fa-sign-in"></i></a></li>
                {%else%}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><i class="fa fa-user-circle-o"></i> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {%if request.user.is_staff %}
                            <li><a href="/admin/"><i class="fa fa-cogs"></i> {%trans "Admin"%}</a></li>
                            <li class="divider"></li>
                        {%endif%}
                        <li><a href="{% url 'basetheme_bootstrap:account'%}"><i class="fa fa-user-circle-o"></i> {%trans "Account"%}</a></li>
                        <li><a href="{% url 'basetheme_bootstrap:logout'%}"><i class="fa fa-sign-out"></i> {%trans "Logout"%}</a></li>
                    </ul>
                </li>
                {%endif%}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<main role="main" class="{% block container-class %}container{% endblock %}">
    <div class="row">
        {% block whole_content_page_title %}
        <div class="page-header">
            {% block content_page_title %}
            <div class="col-xs-12">
                <h1>{% block page_title %}{% endblock %}</h1>
            </div>
            {% endblock %}
            <div class="col-xs-12">
                <hr>
            </div>
        </div>
        {% endblock %}
        {% if messages %}
        <div class="col-xs-12 ">
            {% for message in messages %}
            <p class="alert alert-{{ message.tags|tags_to_bootstrap }}">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message|linebreaksbr}}
            </p>
            {% endfor %}
        </div>
        <div class="col-xs-12">
            <hr>
        </div>
        {% endif %}
        <div class="clearfix"></div>
        {% block content %}{% endblock %}
    </div>
</main>

    <footer class="footer">
      <div class="container">
        <!--<span class="text-muted">Place sticky footer content here.</span>-->
        <span class="text-muted pull-right">
            {% include_if_exists "last_update.html"|localize_template "basetheme_bootstrap/last_update.example.html" %}
        </span>
      </div>
    </footer>
</body>
</html>

basetheme_bootstrap/templates/basetheme_bootstrap/credits.example.html
{% load basetheme_bootstrap %}
{% load i18n %}
<li class="nav-item "><a href="https://www.pasteur.fr/" target="_blank" class="nav-link">{%trans "L'Institut Pasteur"%}</a></li>
<li class="nav-item "><a href="https://research.pasteur.fr/fr/team/bioinformatics-and-biostatistics-hub/" target="_blank" class="nav-link">{%trans "Bioinformatics and Biostatistics HUB"%}</a></li>

basetheme_bootstrap/templates/basetheme_bootstrap/fork_me.example.html
{% load i18n %}
<!-- **** Begin Fork-Me-On-Gitlab-Ribbon-HTML. See MIT License at https://gitlab.com/seanwasere/fork-me-on-gitlab **** -->
<a href="[Your Repository URL Here]">
    <span class="fork_me">{%trans "Fork Me"%}</span>
</a>
<!-- **** End Fork-Me-On-Gitlab-Ribbon-HTML **** -->

basetheme_bootstrap/templates/basetheme_bootstrap/form_host.html
{% extends basetheme_bootstrap_base_template %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block extra_js %}
{{block.super}}
{% if extra_js_file %}
<script src="{% static extra_js_file %}"></script>
{% endif%}
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block page_title %}{{ page_title|default:title }}{% endblock %}

{% block content %}
<div class="col-12 col-xs-12">
    {%if form_title%}<h2>{{form_title}}</h2>{%endif%}
    {% block form %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {%if form%}
        {%if form.forms%}
				{{ form.management_form }}
        <div class="row col-12">
            {% for f in form.forms %}
            <div class="{{ formset_css_classes|default:'mb-4'}}">
                <div class="card">
                    <div class="card-body">
                        {{ f|crispy }}
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
        {%else%}
        {{ form|crispy }}
        {%endif%}
        {%endif%}
        {%if cancel_url%}
        <a role="button" class="btn btn-primary" href="{{cancel_url}}">{{ cancel_text|default:"Cancel"}}</a>
        {%endif%}
        <div class="form-class {{btn_container_classes|default:'pull-right float-right'}}">
            <button class="{{btn_classes|default:'btn btn-primary'}}" type="submit">{{ submit_text|default:"OK" }}</button>
        </div>
    </form>
    {% endblock form %}
</div>
{% endblock %}

basetheme_bootstrap/templates/basetheme_bootstrap/last_update.example.html
In the <i>last_update.html</i> you can for example use a git hook (post-commit and post-merge) running: "<code>echo "Version $(git describe --tags) on $(git show -s --format=%ci)" > ...../templates/my_project/last_update.html</code>" and you will get "Version v1.0.1-40-gc2bc714 on 2018-10-09 19:39:01 +0200"

basetheme_bootstrap/templates/basetheme_bootstrap/logo_left.example.html
{% load  sstatic %}
<img src="{% sstatic '/img/institut-pasteur-logo-2020.png'%}" alt="Accueil">